from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from datetime import datetime

def generate_pdf_report(path, revenue, orders, products, top_quantity, top_revenue, username="Akbar Hossain"):
    c = canvas.Canvas(path, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, height - 50, "🛒 Sales Basket Summary Report")

    # Metadata
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 70, f"Generated by: {username}")
    c.drawString(400, height - 70, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")

    # Summary
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 110, "📊 Summary Stats")
    c.setFont("Helvetica", 12)
    c.drawString(60, height - 130, f"Total Revenue: £{int(revenue):,}")
    c.drawString(60, height - 150, f"Unique Orders: {orders}")
    c.drawString(60, height - 170, f"Unique Products: {products}")

    # Top Quantity
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 210, "🔝 Top Products by Quantity")
    c.setFont("Helvetica", 11)
    y = height - 230
    for item, qty in top_quantity.items():
        c.drawString(60, y, f"{item[:35]:35}  -  {qty}")
        y -= 15

    # Top Revenue
    y -= 15
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "💰 Top Products by Revenue")
    y -= 20
    c.setFont("Helvetica", 11)
    for item, rev in top_revenue.items():
        c.drawString(60, y, f"{item[:35]:35}  -  £{int(rev):,}")
        y -= 15

    c.setStrokeColor(colors.grey)
    c.line(40, y - 10, width - 40, y - 10)

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 30, "Sales Basket · Made by Akbar Hossain · Powered by Streamlit")

    c.save()
